# Generated by Django 3.1.2 on 2022-02-08 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
