# Generated by Django 3.1.2 on 2022-02-08 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment_app', '0002_auto_20220209_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='Email',
            field=models.EmailField(max_length=100, unique=True),
        ),
    ]
