# Generated by Django 3.1.2 on 2022-02-09 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment_app', '0003_auto_20220209_0154'),
    ]

    operations = [
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idname', models.IntegerField()),
                ('email', models.EmailField(max_length=100)),
                ('comment', models.TextField(max_length=1000)),
            ],
        ),
    ]
