# Generated by Django 3.1.2 on 2022-02-09 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment_app', '0005_remove_comment_email'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='comment',
            new_name='comm',
        ),
    ]
