# Generated by Django 3.1.2 on 2022-02-09 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment_app', '0006_auto_20220209_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='comm',
            name='Email',
            field=models.EmailField(default='sample@gmail.com', max_length=100),
        ),
    ]
